[package]
name = "lidi-bindings"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["dylib"]

[dependencies.lidi-clients]
path = "../lidi-clients"
default-features = false

[features]
default = [ "hash", "inotify" ]
hash = [ "lidi-clients/hash" ]
inotify = [ "lidi-clients/inotify" ]
