name: Clippy

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-check:
    name: Run clippy
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust

      - name: Run clippy
        run: just clippy
