name: Tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test-features:
    name: Run build check for all features
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust

      - name: Install cargo hack
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall -y cargo-hack

      - name: Build all features
        run: just cargo-hack

  tests:
    name: Run tests
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust
        with:
          extra-packages: python3-pip python3-virtualenv valgrind

      - name: Get admin permissions for tc
        run: sudo setcap cap_net_admin+ep /usr/sbin/tc

      - name: Create virtualenv
        run: virtualenv venv

      - name: Install python packages
        run: |
          source venv/bin/activate
          pip install behave psutil

      - name: Run tests
        run: |
          source venv/bin/activate
          just test
